name: Update Video RSS

on:
  schedule:
    - cron: '0 */24 * * *' # A cada 6 horas
  workflow_dispatch:      # Permite rodar manualmente

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests feedgen

    - name: Generate Video RSS
      run: python json_feed.py

    - name: Commit and Push
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add feed_video_jw.xml
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update video feed" && git push)
